### ISSUE TITLE
Issue procedure and workflow

### ISSUE THREAD

**Issue by active-sludge** [active-sludge/swe574-group2#3]
A procedure for issue creating and lifecycle will be prepared.

**Comment by semihsolmaz** [comment]
Ststus isimlerinde bir düzeltme yapalım review eden ile test eden aynı olacak temiştik test statusu sanki atıl kalmıs. Ona tested vs diyelim testin bittigini işaret etsin.

Ben ona göre çizdim farklı birşey yapacaksak düzenleriz.
